"""Build module registry from Make.com integration page snapshots.

Data scraped from https://www.make.com/en/integrations/{app-slug} pages.
Re-scrape by running `boost catalog refresh --source web`.
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Any

# ---------------------------------------------------------------------------
# Raw scraped data  (display name -> module ID via _display_to_id)
# For apps where the actual module IDs are confirmed, they are stored directly.
# For others, display names are stored and converted at build time.
# ---------------------------------------------------------------------------

#: Apps whose module names are stored as confirmed action IDs (not display labels).
_CONFIRMED_ID_APPS: set[str] = {
    "anthropic-claude",
    # Built-in platform modules — IDs are stable and known exactly
    "gateway",
    "http",
    "builtin",
    "util",
    "json",
    "code",
}

#: Mapping: app_slug -> {"title": str, "modules": list[str]}
#  For confirmed-ID apps the list contains actual IDs; for others, display names.
SCRAPED_APPS: dict[str, dict[str, Any]] = {
    # ---- Built-in / platform modules (always available) --------------------
    "gateway": {
        "title": "Gateway (Webhooks)",
        "modules": [
            "CustomWebHook",
            "WebhookRespond",
        ],
    },
    "http": {
        "title": "HTTP",
        "modules": [
            "ActionSendData",
            "ActionSendDataAPIKeyAuth",
            "ActionSendDataBasicAuth",
            "ActionSendDataClientCertAuth",
            "MakeRequest",
        ],
    },
    "builtin": {
        "title": "Flow Control",
        "modules": [
            "BasicRouter",
            "BasicAggregator",
        ],
    },
    "util": {
        "title": "Tools",
        "modules": [
            "SetVariables",
            "SetVariable2",
            "FunctionSleep",
            "FunctionIncrement",
            "TextAggregator",
        ],
    },
    "json": {
        "title": "JSON",
        "modules": [
            "CreateJSON",
            "ParseJSON",
            "TransformToJSON",
        ],
    },
    "code": {
        "title": "Code",
        "modules": [
            "ExecuteCode",
        ],
    },
    # ---- AI / LLM -----------------------------------------------------------
    "anthropic-claude": {
        "title": "Anthropic Claude",
        "modules": [
            "createAMessage",
            "createSkill",
            "createSkillVersion",
            "deleteFile",
            "deleteSkill",
            "deleteSkillVersion",
            "downloadFile",
            "getFile",
            "getSkill",
            "getSkillVersion",
            "makeAnApiCall",
            "simpleTextPrompt",
            "uploadFile",
            "listFiles",
            "listSkills",
            "listSkillVersions",
        ],
    },
    "openai-gpt-3": {
        "title": "OpenAI (GPT-3, DALL-E & Whisper)",
        "modules": [
            "Watch batch completed",
            "Watch video jobs",
            "Add files to a vector store",
            "Analyze images (Vision)",
            "Cancel a batch",
            "Create a batch",
            "Delete a conversation",
            "Delete a response",
            "Delete a video",
            "Download a container file",
            "Edit images",
            "Generate a completion",
            "Generate a moderation",
            "Generate a response",
            "Generate a transcription",
            "Generate a translation (Whisper)",
            "Generate a video",
            "Generate images",
            "Generate speech from text",
            "Get a batch",
            "Get a response",
            "Get a video",
            "Make an API call",
            "Message an assistant",
            "Remix a video",
            "Simple text prompt",
            "Transform text to structured data",
            "Upload a file",
            "List batches",
            "List input items",
            "List video jobs",
        ],
    },
    # ---- Google Workspace ---------------------------------------------------
    "google-sheets": {
        "title": "Google Sheets",
        "modules": [
            "Perform a Function",
            "Watch Changes",
            "Watch New Rows",
            "Add a Conditional Format Rule",
            "Add a Row",
            "Add a Sheet",
            "Bulk Add Rows (Advanced)",
            "Bulk Update Rows (Advanced)",
            "Clear a Cell",
            "Clear a Row",
            "Clear Values from a Range",
            "Copy a Sheet",
            "Create a Spreadsheet",
            "Create a Spreadsheet from a Template",
            "Delete a Conditional Format Rule",
            "Delete a Row",
            "Delete a Sheet",
            "Get a Cell",
            "Make an API Call",
            "Perform a Function - Responder",
            "Rename a Sheet",
            "Update a Cell",
            "Update a Row",
            "Get Range Values",
            "List Sheets",
            "Search Rows",
            "Search Rows (Advanced)",
        ],
    },
    "google-drive": {
        "title": "Google Drive",
        "modules": [
            "Watch All Files",
            "Watch Comments",
            "Watch Files in a Folder",
            "Watch Folders",
            "Watch Shared Drives",
            "Copy a File",
            "Create a File from Text",
            "Create a File/Folder Shortcut",
            "Create a Folder",
            "Create a Shared Drive",
            "Delete a File/Folder",
            "Delete a File Revision",
            "Delete a Shared Drive",
            "Download a File",
            "Get a File/Folder Path for an ID",
            "Get a File Revision",
            "Get a Shared Drive",
            "Get a Share Link",
            "Make an API Call",
            "Move a File/Folder",
            "Move a File/Folder to Trash",
            "Rename a Folder",
            "Revoke a File/Folder Access",
            "Update a File",
            "Update a File/Folder Access",
            "Update a File Revision",
            "Update a Shared Drive",
            "Upload a File",
            "Get a Folder ID for a Path",
            "List File Revisions",
            "Search for Files/Folders",
            "Search for Shared Drives",
        ],
    },
    "google-docs": {
        "title": "Google Docs",
        "modules": [
            "Watch Documents",
            "Create a Document",
            "Create a Document from a Template",
            "Delete a Document",
            "Download a Document",
            "Get Content of a Document",
            "Insert a Paragraph to a Document",
            "Insert an Image to a Document",
            "Make All Links in a Document Clickable",
            "Make an API Call",
            "Replace an Image with a New Image",
            "Replace a Text in a Document",
            "List Documents",
        ],
    },
    "google-calendar": {
        "title": "Google Calendar",
        "modules": [
            "Watch Events",
            "Clear a Calendar",
            "Create a Calendar",
            "Create an Access Control Rule",
            "Create an Event",
            "Delete a Calendar",
            "Delete an Access Control Rule",
            "Delete an Event",
            "Duplicate an Event",
            "Get a Calendar",
            "Get an Access Control Rule",
            "Get an Event",
            "Get Free/Busy Information",
            "Make an API Call",
            "Update a Calendar",
            "Update an Access Control Rule",
            "Update an Event",
            "List Access Control Rules",
            "List Calendars",
            "Search Events",
        ],
    },
    # ---- Social Media -------------------------------------------------------
    "linkedin": {
        "title": "LinkedIn",
        "modules": [
            "Watch Company Posts",
            "Create a Company Image Post",
            "Create a Company Text Post",
            "Create a Company Video Post",
            "Create a User Image Post",
            "Create a User Text Post",
            "Create a User Video Post",
            "Delete a Company Post",
            "Delete a User Post",
            "Get a Company Post",
            "Get the Company Share Statistics",
            "Get the Follower Statistics",
            "Get the Page Statistics",
            "Make an API Call",
            "Get the Company Share Statistics over Time",
            "Get the Follower Statistics over Time",
            "Get the Page Statistics over Time",
            "Get the Statistics of Shares",
            "List Company Posts",
        ],
    },
    "instagram-business": {
        "title": "Instagram for Business",
        "modules": [
            "Watch events",
            "Watch media",
            "Watch public user posts",
            "Create a carousel post",
            "Create a comment",
            "Create a photo post",
            "Create a reel post",
            "Create a reply",
            "Download media",
            "Get post",
            "Get public user info",
            "Get carousel media",
            "Get post insights",
            "Get user insights",
            "List comment replies",
            "List post comments",
            "List posts",
            "List public user posts",
            "List stories",
        ],
    },
    "facebook-pages": {
        "title": "Facebook Pages",
        "modules": [
            "Watch Comments",
            "Watch Photos",
            "Watch Posts",
            "Watch Posts (public page)",
            "Watch Videos",
            "Create a Comment",
            "Create a Post",
            "Create a Post with Photos",
            "Delete a Comment",
            "Delete a Photo",
            "Delete a Post",
            "Delete a Video",
            "Edit a Comment",
            "Edit a Post",
            "Get a Comment",
            "Get a Page",
            "Get a Photo",
            "Get a Post",
            "Get a Video",
            "Get Post Reactions",
            "Like a Post",
            "Publish a Reel",
            "Unlike a Post",
            "Update a Video",
            "Update Page Details",
            "Upload a Photo",
            "Upload a Video",
            "List Comments",
            "List Photos",
            "List Posts",
            "List Videos",
        ],
    },
    "facebook-lead-ads": {
        "title": "Facebook Lead Ads",
        "modules": [
            "New Lead",
            "Watch Leads",
            "Get Lead Details",
            "Get a Form",
            "Unsubscribe a Webhook",
            "List Leads",
        ],
    },
    "youtube": {
        "title": "YouTube",
        "modules": [
            "Watch New Comments",
            "Watch Videos by Search",
            "Watch Videos in a Channel",
            "Watch Videos in a Playlist",
            "Add a Video to the Playlist",
            "Create a Playlist",
            "Delete a Playlist",
            "Delete a Video",
            "Make an API Call",
            "Reply to a Comment",
            "Set a Video Thumbnail",
            "Update a Channel Banner",
            "Update a Channel Details",
            "Update a Playlist",
            "Update a Video Details",
            "Upload a Video",
        ],
    },
    "discord": {
        "title": "Discord",
        "modules": [
            "Watch Channel Invites",
            "Watch Channel Messages",
            "Watch Guild Members",
            "Add a Role to a Guild Member",
            "Create a Channel Invite",
            "Create a Channel Thread",
            "Create a Guild Channel",
            "Create a Guild Event",
            "Create a Webhook Bot",
            "Delete a Channel",
            "Delete a Guild Event",
            "Delete a Message",
            "Delete a Webhook Bot",
            "Edit a Message",
            "Get a Guild Event",
            "Get a Message",
            "Make an API Call",
            "Post a Reaction with an Emoji",
            "Remove a Role from a Guild Member",
            "Send a Message",
            "Send a Message by Webhook Bot",
            "Update a Channel",
            "Update a Current Bot",
            "Update a Guild Event",
            "Update a Guild Member",
            "List Channel Invites",
            "List Channel Messages",
            "List Channels",
            "List Guild Events",
            "List Guild Members",
            "List Guild Members with Reactions on Message",
            "Search Guild Members",
        ],
    },
    "whatsapp-business-cloud": {
        "title": "WhatsApp Business Cloud",
        "modules": [
            "Watch Events",
            "Deregister a Sender",
            "Download a Media",
            "Enable Two-Step Verification",
            "Get a Business Profile",
            "Register a Sender",
            "Send a Message",
            "Send a Template Message",
            "Update a Business Profile",
            "Upload a Media",
            "Verify a Sender",
        ],
    },
    # ---- Messaging / Comms --------------------------------------------------
    "slack": {
        "title": "Slack",
        "modules": [
            "Watch Direct Messages",
            "Watch Files",
            "Watch Multiparty Direct Messages",
            "Watch New Events",
            "Watch Private Channel Messages",
            "Watch Public Channel Messages",
            "Watch Users",
            "Add a Reaction",
            "Add a Star",
            "Archive a Channel",
            "Create a Channel",
            "Create a Reminder",
            "Delete a File",
            "Delete a Message",
            "Edit a Message",
            "Get a Channel",
            "Get a File",
            "Get a Private Channel Message",
            "Get a Public Channel Message",
            "Get a User",
            "Invite Users",
            "Join a Channel",
            "Kick a User",
            "Leave a Channel",
            "Make an API Call",
            "Pin a Message",
            "Remove a Reaction",
            "Remove a Star",
            "Remove Saved Item",
            "Save an Item",
            "Send a File Message",
            "Send a Message",
            "Set a Status",
            "Set the Purpose of a Channel",
            "Set the Topic of a Channel",
            "Unarchive a Channel",
            "Unpin a Message",
            "Upload a File",
            "List Channels",
            "List Files",
            "List Members in a Channel",
            "List Reactions",
            "List Replies",
            "List Users",
            "Search for Message",
            "Search for User",
        ],
    },
    # ---- CRM / Sales --------------------------------------------------------
    "hubspotcrm": {
        "title": "HubSpot CRM",
        "modules": [
            "Watch Companies",
            "Watch Contacts",
            "Watch CRM Objects",
            "Watch Deals",
            "Watch Files",
            "Watch Members Added to a List",
            "Watch Notifications",
            "Watch Submissions for a Form",
            "Watch Tickets",
            "Create a Company",
            "Create a Contact",
            "Create a Custom Object Record",
            "Create a Deal",
            "Create a Note",
            "Create a Task",
            "Create a Ticket",
            "Create or Update a Contact",
            "Update a Company",
            "Update a Contact",
            "Update a Custom Object Record",
            "Update a Deal",
            "Update a Task",
            "Update a Ticket",
            "Delete a Company",
            "Delete a Contact",
            "Delete a Deal",
            "Delete a Task",
            "Delete a Ticket",
            "Get a Company",
            "Get a Contact",
            "Get a Custom Object Record",
            "Get a Deal",
            "Get a Task",
            "Get a Ticket",
            "Add Members to a List",
            "Make an API Call",
            "Merge Contacts",
            "Submit Data to a Form",
            "Upload a File",
        ],
    },
    "salesforce": {
        "title": "Salesforce",
        "modules": [
            "Watch Jobs",
            "Watch Record Fields",
            "Watch Records",
            "Complete/Abort a Job",
            "Create a Job",
            "Create a Record",
            "Delete a Record",
            "Download an Attachment/Document",
            "Get a Record",
            "Make an API Call",
            "Make an API Call (Advanced)",
            "Post a Message to a Chatter Feed",
            "Update a Record",
            "Upsert a Record",
            "List Jobs",
            "Search Records (SOQL)",
            "Search Records (SOSL)",
        ],
    },
    # ---- Project Management -------------------------------------------------
    "airtable": {
        "title": "Airtable",
        "modules": [
            "Watch Records",
            "Watch Responses",
            "Bulk Delete Records (advanced)",
            "Create a Record",
            "Delete a Record",
            "Get a Record",
            "Make an API Call",
            "Update a Record",
            "Upsert a Record",
            "Bulk Create Records (advanced)",
            "Bulk Update Records (advanced)",
            "Bulk Upsert Records (advanced)",
            "Search Records",
        ],
    },
    "notion": {
        "title": "Notion",
        "modules": [
            "Watch Data Source Items",
            "Watch Events",
            "Watch Objects",
            "Watch Page Contents",
            "Append a Data Source Item Content",
            "Append a Page Content",
            "Create a Database",
            "Create a Data Source",
            "Create a Data Source Item",
            "Create a Page",
            "Delete a Page Content",
            "Get a Database",
            "Get a Data Source",
            "Get a Data Source Item",
            "Get a Page",
            "Get a Page Content",
            "Make an API Call",
            "Update a Database",
            "Update a Data Source",
            "Update a Data Source Item",
            "Update a Page",
            "Update a Page Content",
            "List Page Contents",
            "List Page Property Items",
            "List Users",
            "Search Objects",
        ],
    },
    "trello": {
        "title": "Trello",
        "modules": [
            "Watch Activities",
            "Watch Cards",
            "Watch Cards Moved to a List",
            "Watch Comments",
            "Watch Notifications",
            "Add a Label to a Card",
            "Add a Member to a Card",
            "Add an Attachment",
            "Create a Board",
            "Create a Card",
            "Create a Checklist",
            "Create a Label",
            "Create a List",
            "Delete a Card",
            "Delete a Checklist",
            "Delete a Label",
            "Edit a Board",
            "Edit a Card",
            "Edit a Label",
            "Edit a List",
            "Get a Board",
            "Get a Card",
            "Get a Checklist",
            "Get a Label",
            "Get a List",
            "Make an API Call",
            "Remove a Label from a Card",
            "Remove a Member from a Card",
            "Get Board Lists",
            "Get Card Checklists",
            "List Labels",
            "Search for Boards",
            "Search for Cards",
            "Search for Members",
        ],
    },
    "clickup": {
        "title": "ClickUp",
        "modules": [
            "Watch Folders",
            "Watch Lists",
            "Watch Spaces",
            "Watch Tasks",
            "Add Tracked Time",
            "Create a Checklist",
            "Create a Folder",
            "Create a Goal",
            "Create a List",
            "Create a Space",
            "Create a Task",
            "Delete Folder",
            "Delete List",
            "Delete Space",
            "Delete Task",
            "Delete Time Entry",
            "Edit Folder",
            "Edit Goal",
            "Edit List",
            "Edit Space",
            "Edit Task",
            "Get Folder",
            "Get Goal",
            "Get List",
            "Get Space",
            "Get Task",
            "Get Time Entry",
            "Post Chat Message",
            "Post Comment to Task",
            "Update Comment",
            "Update Time Entry",
            "Upload Task Attachment",
        ],
    },
    "monday": {
        "title": "Monday.com",
        "modules": [
            "Watch Board's Items",
            "Watch Events",
            "Watch Group's Items",
            "Watch Item's Column Value",
            "Watch Item's Updates",
            "Add Board Subscribers",
            "Add a Column to a Board",
            "Create a Board",
            "Create a Group",
            "Create a Notification",
            "Create a Subitem",
            "Create an Item",
            "Create an Update",
            "Delete or Archive an Item",
            "Download a File",
            "Duplicate a Board",
            "Duplicate an Item",
            "Execute a GraphQL Query",
            "Get a Board",
            "Get a Group",
            "Get an Item",
            "Get a User",
            "Move an Item Between Groups",
            "Update Column Values of a Specific Item",
            "List Boards",
            "List Board's Groups",
            "List Board's Items",
            "List Users",
            "Search Items in the Board by Column Values",
        ],
    },
    "asana": {
        "title": "Asana",
        "modules": [
            "Watch Completed Tasks",
            "Watch New Projects",
            "Watch New Tasks",
            "Watch Tasks or Subtasks",
            "Watch Webhook Events",
            "Add a Task to a Project",
            "Create a Portfolio",
            "Create a Project",
            "Create a Project Section",
            "Create a Tag",
            "Create a Task or a Subtask",
            "Create a Team",
            "Delete a Portfolio",
            "Delete a Project",
            "Delete a Task",
            "Duplicate a Project",
            "Duplicate a Task",
            "Get a Portfolio",
            "Get a Project",
            "Get a Task",
            "Get a Team",
            "Get a User",
            "Get a Workspace",
            "Make an API Call",
            "Remove a Task from a Project",
            "Update a Portfolio",
            "Update a Project",
            "Update a Task",
            "List Projects",
            "List Tags",
            "List Tasks",
            "List Users",
            "List Workspaces",
        ],
    },
    "jira": {
        "title": "Jira Software",
        "modules": [
            "Watch Issues",
            "Add an Attachment",
            "Add an Issue Comment",
            "Add a Watcher",
            "Assign/Unassign an Issue",
            "Create a Component",
            "Create an Issue",
            "Create an Issue Link",
            "Create a Project Version",
            "Delete a Component",
            "Delete an Attachment",
            "Delete an Issue",
            "Delete an Issue Comment",
            "Delete an Issue Link",
            "Delete a Project Version",
            "Download an Attachment",
            "Get an Issue",
            "Get an Issue Comment",
            "Make an API Call",
            "Update a Component",
            "Update an Issue",
            "Update an Issue Comment",
            "Update an Issue Status (Transition Issue)",
            "Update a Project Version",
            "List Issue Comments",
            "List Project Components",
            "List Project Versions",
            "List Users",
            "Search Issues",
            "Search Users",
        ],
    },
    # ---- Dev Tools ----------------------------------------------------------
    "github": {
        "title": "GitHub",
        "modules": [
            "Watch Branches",
            "Watch Commits",
            "Watch Issues",
            "Watch Milestones",
            "Watch Pull Requests",
            "Watch Releases",
            "Watch Repositories",
            "Add Assignees",
            "Add Labels",
            "Create a Comment",
            "Create an Issue",
            "Delete a Comment",
            "Delete an Issue",
            "Delete Assignees",
            "Execute a GraphQL Query",
            "Get a Branch",
            "Get a Comment",
            "Get an Issue",
            "Get an Organization",
            "Get a Pull Request",
            "Get a Release",
            "Get a Repository",
            "Get a User",
            "Update a Comment",
            "Update an Issue",
            "Search Assignees",
            "Search Branches",
            "Search Issues",
            "Search Milestones",
            "Search Pull Requests",
            "Search Releases",
        ],
    },
    "gitlab": {
        "title": "GitLab",
        "modules": [
            "Watch Issues",
            "Watch Jobs",
            "Watch Merge Requests",
            "Watch Pipelines",
            "Watch Projects",
            "Watch Push Events",
            "Watch Tags",
            "Accept a Merge Request",
            "Cancel a Job",
            "Cancel a Pipeline's Jobs",
            "Create a File in a Repository",
            "Create a Label",
            "Create a Merge Request",
            "Create a Milestone",
            "Create an Issue",
            "Create an Issue Note",
            "Create a Pipeline",
            "Create a Release",
            "Create a Repository Branch",
            "Create a Tag",
            "Delete a File in a Repository",
            "Delete an Issue",
            "Delete a Repository Branch",
            "Delete a Tag",
            "Execute a GraphQL Query",
            "Get a Commit",
            "Get a Job",
            "Get a Merge Request",
            "Get a Milestone",
            "Get an Issue",
            "Get a Pipeline",
            "Get a Project",
            "Get a Repository Branch",
            "Get a User",
            "Make an API Call",
            "Play a Job",
            "Update a Merge Request",
            "Update a Milestone",
            "Update an Issue",
            "List Issues",
            "List Milestones",
            "List Merge Requests",
            "List Pipelines",
            "Search Issues",
            "Search Projects",
            "Search Users",
        ],
    },
    # ---- Storage / Files ----------------------------------------------------
    "dropbox": {
        "title": "Dropbox",
        "modules": [
            "Watch Files",
            "Copy a File or Folder",
            "Create a File Request",
            "Create a Folder",
            "Create/Overwrite a Text file",
            "Create/Update a Share Link",
            "Delete a File/Folder",
            "Download a File",
            "Get a File Request",
            "Make an API Call",
            "Move a File/Folder",
            "Rename a File/Folder",
            "Restore a File",
            "Upload a File",
            "List All Files/Subfolders In a Folder",
            "List File Revisions",
            "Search Files/Folders",
        ],
    },
    # ---- Marketing ----------------------------------------------------------
    "mailchimp": {
        "title": "Mailchimp",
        "modules": [
            "Watch Campaigns",
            "Watch Lists",
            "Watch Subscribers",
            "Watch Unsubscribes",
            "Add/Update a Subscriber",
            "Create a Campaign",
            "Create a List",
            "Delete a Campaign",
            "Delete a List",
            "Edit a Subscriber",
            "Get a Campaign",
            "Get a Campaign Report",
            "Get a List",
            "Get a Subscriber",
            "Make an API Call",
            "Perform a Campaign Action",
            "Update a Campaign",
            "Update a List",
            "Search Campaigns",
            "Search Lists",
            "Search Subscribers",
        ],
    },
    # ---- Payments -----------------------------------------------------------
    "stripe": {
        "title": "Stripe",
        "modules": [
            "Watch Events",
            "Cancel a Payment Intent",
            "Capture a Payment Intent",
            "Confirm a Payment Intent",
            "Create a Customer",
            "Create a Payment Intent",
            "Create a Refund",
            "Create an Invoice",
            "Create an Invoice Item",
            "Delete a Customer",
            "Delete a Draft Invoice",
            "Finalize a Draft Invoice",
            "Make an API Call",
            "Retrieve a Customer",
            "Retrieve a Payment Intent",
            "Retrieve a Refund",
            "Retrieve an Invoice",
            "Update a Customer",
            "Update a Payment Intent",
            "Update a Refund",
            "Update an Invoice",
            "Void an Invoice",
            "List All Customers",
            "List Payment Intents",
            "Search Customers",
            "Search Invoices",
        ],
    },
    # ---- E-Commerce ---------------------------------------------------------
    "shopify": {
        "title": "Shopify",
        "modules": [
            "Watch events",
            "Watch orders",
            "Watch products",
            "Adjust an inventory level",
            "Create a customer",
            "Create a fulfillment",
            "Create an order",
            "Create a product",
            "Create a product variant",
            "Get a customer",
            "Get an order",
            "Get a product",
            "Get a product variant",
            "Make a GraphQL API call",
            "Make a REST API call",
            "Update a customer",
            "Update an order",
            "Update a product",
            "Update a product variant",
            "Search customers",
            "Search orders",
            "Search products",
        ],
    },
}

# ---------------------------------------------------------------------------
# Known exact module ID overrides
# Use these when the display name → ID conversion would produce a wrong result.
# Format: "app-slug:displayName" -> "app-slug:exactModuleId"
# ---------------------------------------------------------------------------
_ID_OVERRIDES: dict[str, str] = {
    # Google Sheets - confirmed from tenant blueprints
    "google-sheets:Watch New Rows": "google-sheets:watchRows",
    "google-sheets:Add a Row": "google-sheets:addRow",
    "google-sheets:Update a Row": "google-sheets:updateRow",
    "google-sheets:Search Rows": "google-sheets:searchRows",
    "google-sheets:Search Rows (Advanced)": "google-sheets:searchRowsWithFilters",
    "google-sheets:Get a Cell": "google-sheets:getCell",
    "google-sheets:Update a Cell": "google-sheets:updateCell",
    "google-sheets:Clear a Row": "google-sheets:clearRow",
    "google-sheets:Delete a Row": "google-sheets:deleteRow",
    "google-sheets:Add a Sheet": "google-sheets:addSheet",
    "google-sheets:Delete a Sheet": "google-sheets:deleteSheet",
    "google-sheets:Create a Spreadsheet": "google-sheets:createSpreadsheet",
    "google-sheets:List Sheets": "google-sheets:listSheets",
    "google-sheets:Get Range Values": "google-sheets:getRangeValues",
    "google-sheets:Make an API Call": "google-sheets:makeApiCall",
    # LinkedIn - confirmed from tenant blueprint (scenario 125626)
    "linkedin:Create a User Text Post": "linkedin:CreatePost",
    "linkedin:Create a Company Text Post": "linkedin:CreateCompanyPost",
    "linkedin:Create a User Image Post": "linkedin:CreateImagePost",
    "linkedin:Create a Company Image Post": "linkedin:CreateCompanyImagePost",
    "linkedin:Make an API Call": "linkedin:makeApiCall",
    "linkedin:Watch Company Posts": "linkedin:TriggerNewCompanyPost",
    "linkedin:List Company Posts": "linkedin:SearchCompanyPosts",
    # OpenAI - common modules
    "openai-gpt-3:Generate a completion": "openai-gpt-3:CreateCompletion",
    "openai-gpt-3:Simple text prompt": "openai-gpt-3:SimpleTextPrompt",
    "openai-gpt-3:Make an API call": "openai-gpt-3:makeApiCall",
    "openai-gpt-3:Generate a response": "openai-gpt-3:GenerateResponse",
    "openai-gpt-3:Message an assistant": "openai-gpt-3:MessageAssistant",
    "openai-gpt-3:Generate images": "openai-gpt-3:GenerateImage",
}


def _display_to_id(display: str) -> str:
    """Convert a display name to a camelCase module ID.

    Examples:
        "Create a Photo Post" -> "createAPhotoPost"
        "Watch Events"        -> "watchEvents"
        "Make an API Call"    -> "makeAnApiCall"
        "Get a User"          -> "getAUser"
    """
    # Normalise: strip special chars except spaces
    cleaned = re.sub(r"[^a-zA-Z0-9 ]+", "", display).strip()
    words = cleaned.split()
    if not words:
        return "unknown"
    result = words[0].lower()
    for word in words[1:]:
        result += word[0].upper() + word[1:] if word else ""
    return result


def build_registry_from_web_snapshot() -> dict[str, Any]:
    """Build a full module registry from the static web snapshot."""
    modules: dict[str, dict[str, Any]] = {}
    apps: dict[str, dict[str, Any]] = {}

    for app_slug, app_data in SCRAPED_APPS.items():
        app_title = str(app_data.get("title", app_slug))
        module_names: list[str] = app_data.get("modules", [])
        confirmed_ids = app_slug in _CONFIRMED_ID_APPS
        module_ids: list[str] = []

        for display in module_names:
            override_key = f"{app_slug}:{display}"
            if override_key in _ID_OVERRIDES:
                module_id = _ID_OVERRIDES[override_key]
            elif confirmed_ids:
                # display IS the ID
                module_id = f"{app_slug}:{display}"
            else:
                action_id = _display_to_id(display)
                module_id = f"{app_slug}:{action_id}"

            modules[module_id] = {
                "id": module_id,
                "app": app_slug,
                "name": module_id.split(":", 1)[1] if ":" in module_id else module_id,
                "title": display,
                "latestVersion": 1,
                "versions": [1],
                "mapperFields": [],
            }
            module_ids.append(module_id)

        apps[app_slug] = {
            "id": app_slug,
            "title": app_title,
            "moduleIds": sorted(set(module_ids)),
        }

    return {
        "meta": {
            "source": "make-web-snapshot",
            "generatedAt": datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
            "packageVersion": "2026-04-08",
            "moduleCount": len(modules),
            "appCount": len(apps),
        },
        "modules": dict(sorted(modules.items(), key=lambda item: item[0].casefold())),
        "apps": dict(sorted(apps.items(), key=lambda item: item[0].casefold())),
    }
